#!/bin/sh
`cowrie install: source https://github.com/micheloosterhof/cowrie/blob/master/INSTALL.md`
`git clone https://github.com/uberemes/honeypot.git`


`prepare cowrie setup`
`update the system`
sudo apt update && sudo apt upgrade -y
`install need packages`
sudo apt install git python-virtualenv libssl-dev libffi-dev build-essential libpython-dev python2.7-minimal authbind supervisor -y

`## Switch SSH (management port to different port example 1234)`
`change port in file /etc/ssh/sshd_config`
cd /etc/ssh && sudo rm sshd_config && sudo wget https://raw.githubusercontent.com/uberemes/honeypot/master/sshd_config
`# port 22`
`-> port 1234`

sudo touch /etc/authbind/byport/22 && sudo chown cowrie /etc/authbind/byport/22 && sudo chmod 777 /etc/authbind/byport/22


`sudo adduser --disabled-password cowrie`
sudo adduser cowrie --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
sudo su - cowrie

`store current dir`
var_pwd=$(pwd)
git clone http://github.com/micheloosterhof/cowrie && cd $var_pwd/cowrie

virtualenv --python=python3 cowrie-env
virtualenv --python=python2 cowrie-env

source cowrie-env/bin/activate
pip install --upgrade pip
pip install --upgrade -r requirements.txt


`### in new terminal as root ###`
`# config file`
`sudo cp $var_pwd/cowrie/etc/cowrie.cfg.dist $var_pwd/cowrie/etc/cowrie.cfg`
cd $var_pwd/cowrie/etc/ && wget https://raw.githubusercontent.com/uberemes/honeypot/master/cowrie.cfg
`manual version` `sudo nano /home/cowrie/cowrie/etc/cowrie.cfg` `#change hostname`

cd $var_pwd/cowrie/data
sudo ssh-keygen -t dsa -b 1024 -f ssh_host_dsa_key


cd /etc/supervisor/conf.d/ && sudo wget https://raw.githubusercontent.com/uberemes/honeypot/master/cowrie.conf

sudo nano $var_pwd/cowrie/bin/cowrie
`# DAEMONIZE=""`
`-> DAEMONIZE="-n"`

`#### test ####`
`[ssh]`
`listen_endpoints = tcp:22:interface=0.0.0.0`
`or`
`# forwards traffic on port 22 -> 2222`
sudo iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 2222
sudo apt-get install iptables-persistent
`# save iptables later state`
`sudo netfilter-persistent save`
`#### test ####`




`#################################################################
##################################################################
###### Default install ###########################################
##################################################################
#################################################################`
`#### START ####`
`cd /home/cowrie/cowrie`
`source cowrie-env/bin/activate`
`/home/cowrie/cowrie/bin/cowrie start`