#!/bin/bash
`wait 1 minute
pi
wait 30 seconds
password
wait 10 seconds
sudo raspi-config
wait 5 seconds
down 4 times
down once
left once
enter
enter
tab
tab
enter
sudo reboot now`


`testing syntax
cowrie install:
source https://github.com/micheloosterhof/cowrie/blob/master/INSTALL.md`

sudo apt update && sudo apt upgrade -y && sudo apt install git python-virtualenv libssl-dev libffi-dev build-essential libpython-dev python2.7-minimal authbind supervisor -y

adduser --disabled-password --gecos "" cowrie
`sudo adduser --disabled-password cowrie`
`[ ] test: sudo adduser cowrie --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password`

`############## usr cowrie ##############`
sudo su - cowrie
git clone http://github.com/micheloosterhof/cowrie && cd cowrie

virtualenv --python=python3 cowrie-env
virtualenv --python=python2 cowrie-env

source cowrie-env/bin/activate
pip install --upgrade pip
pip install --upgrade -r requirements.txt

touch /etc/authbind/byport/22
chown cowrie:cowrie /etc/authbind/byport/22
chmod 770 /etc/authbind/byport/22

`change text in file`
sed -i 's/AUTHBIND_ENABLED=no/AUTHBIND_ENABLED=yes/g' bin/cowrie
sed -i 's/listen_endpoints = tcp:2222:interface=0.0.0.0/listen_endpoints = tcp:22:interface=0.0.0.0/g' cowrie.cfg
`############## usr cowrie ##############`


### in new terminal as root ###
# config file
wget https://raw.githubusercontent.com/uberemes/honeypot/master/cowrie.cfg -P /home/cowrie/cowrie/etc/


cd /home/cowrie/cowrie/data
sudo ssh-keygen -t dsa -b 1024 -f ssh_host_dsa_key

## Switch SSH (management port to different port example 1234)
sudo rm sshd_config -f && sudo wget https://raw.githubusercontent.com/uberemes/honeypot/master/sshd_config -P /etc/ssh/

sudo nano /home/cowrie/cowrie/etc/cowrie.cfg
#change hostname


sudo nano /etc/supervisor/conf.d/cowrie.conf
##### ADD #####
[program:cowrie]
command=/home/cowrie/cowrie/bin/cowrie start
directory=/home/cowrie/cowrie/
user=cowrie
autorestart=true
redirect_stderr=true
################

sudo nano /home/cowrie/cowrie/bin/cowrie
# DAEMONIZE=""
-> DAEMONIZE="-n"

sudo touch /etc/authbind/byport/22
sudo chown cowrie /etc/authbind/byport/22
sudo chmod 777 /etc/authbind/byport/22
sudo nano /home/cowrie/cowrie/bin/cowrie.cfg
->AUTHBIND_ENABLED=yes




##################################################################
##################################################################
###### Default install ###########################################
##################################################################
##################################################################





#### START ####
cd /home/cowrie/cowrie
source cowrie-env/bin/activate
/home/cowrie/cowrie/bin/cowrie start
